logger:
  file: /opt/open5gs/var/log/open5gs/nrf.log

sbi:
  server:
    no_tls: true
  client:
    no_tls: true

nrf:
  sbi:
    - addr: 10.10.0.10
      port: 7777

scp:
  sbi:
    - addr: 10.10.0.11
      port: 7777

parameter:
  no_ipv6: true

max:
  ue: 1024
