supi: 'imsi-001010000000004'
mcc: '001'
mnc: '01'
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
op: 'E8ED289DEBA952E4283B54E88E6183CA'
opType: 'OPC'
amf: '8000'
imei: '356938035643804'
imeiSv: '4370816125816154'
gnbSearchList:
  - 10.10.0.30
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 0x000001
configured-nssai:
  - sst: 1
    sd: 0x000001
default-nssai:
  - sst: 1
    sd: 1
integrity:
  IA1: false
  IA2: false
  IA3: false
ciphering:
  EA1: false
  EA2: false
  EA3: false
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
uacAic:
  mps: false
  mcs: false
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
